name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ github.token }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy_python_flask_starter:
    name: Build and Deploy Python Flask Starter to Wasmer Edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wasmer
        uses: wasmerio/setup-wasmer@v2
      - run: |
          wasmer whoami --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Set up virtual env
        run: |
          python -m venv .env
      - name: Install Flask
        run: |
          pip install --target ./.env/lib/python3.12/site-packages Flask
      # - name: Deploy app to wasmer.wtf
      #   run: wasmer deploy --registry="https://registry.wasmer.wtf/graphql" --token=${{ secrets.WASMER_CIUSER_DEV_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id --owner wasmer-tests
      #   continue-on-error: true
      - name: Deploy app to wasmer.io
        run: wasmer deploy --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
